name:                Mutagen 
version:             0.1.0.0
license:             BSD3

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

dependencies:
- base >= 4.7 && < 5
- haskell-src-exts == 1.21.0
- directory == 1.3.3.0
- pretty-simple == 2.2.0.1
- process == 1.6.3.0
- filepath == 1.4.2.1
- file-embed == 0.0.11
- bytestring == 0.10.8.2
- unix == 2.7.2.2
- path-io == 1.4.2
- path == 0.6.1

library:
  source-dirs: src

executables:
  mutagen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Mutagen 

tests:
  mutagen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Mutagen 
